routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@home')->middleware('auth');
Route::middleware(['approved'])->group(function () {

    Route::get('/home', 'HomeController@home')->name('home');

    
});

Route::group(['middleware' => 'auth'], function () {
   
    //    Route::get('/link1', function ()    {
//        // Uses Auth Middleware
//    });

    //Please do not remove this if you want adminlte:route and adminlte:link commands to works correctly.
    #adminlte_routes
});

Auth::routes();

Route::get('logActivity', 'HomeController@logActivity');
Route::get('get-data-eventos-datatables', ['as'=>'get.eventos','uses'=>'HomeController@getData']);

/* Usuarios */
Route::resource('users', 'UserController');
Route::get('get-data-usuarios-datatables', ['as'=>'get.usuarios','uses'=>'UserController@getData']);

/* Bancos */
Route::resource('bancos', 'BancosController');
Route::get('get-data-bancos-datatables', ['as'=>'get.bancos','uses'=>'BancosController@getData']);

/* Entidades */
Route::resource('entidades', 'EntidadesController');
Route::post('entidades/update','EntidadesController@update')->name('entidades/update');
Route::get('get-data-entidades-datatables', ['as'=>'get.entidades','uses'=>'EntidadesController@getData']);

/* Entidades Banco*/
Route::resource('entidadbanco', 'EntidadesBancoController');
Route::get('get-data-entidades-banco-datatables', ['as'=>'get.entidades.banco','uses'=>'EntidadesController@getDataBanco']);
Route::get('get-data-ent-banco-datatables', ['as'=>'get.ent.banco','uses'=>'EntidadesBancoController@getDataBancoView']);

/* clasificacion admin */
Route::resource('clasificaciones', 'ClasificacionController');
Route::get('get-data-clasificaciones-datatables', ['as'=>'get.clasificaciones','uses'=>'ClasificacionController@getData']);

/* roles */
Route::resource('roles', 'RoleController');

/* permisos */
Route::resource('permissions', 'PermissionController');

/* contenedores operaciones */
Route::resource('contenedores', 'ContenedorController');
Route::get('get-data-contenedores-datatables', ['as'=>'get.contenedores','uses'=>'ContenedorController@getData']);

/* puertos operaciones */
Route::resource('puertos', 'PuertoController');
Route::get('get-data-puertos-datatables', ['as'=>'get.puertos','uses'=>'PuertoController@getData']);

/* catalogo aeropuertos de  operaciones */
Route::resource('airports', 'AeropuertoController');
Route::get('get-data-airports-datatables', ['as'=>'get.airports','uses'=>'AeropuertoController@getData']);

/* catalogo estados de  operaciones */
Route::resource('states', 'EstadoController');
Route::get('get-data-states-datatables', ['as'=>'get.states','uses'=>'EstadoController@getData']);

/* operaciones -- operaciones */
Route::resource('operaciones', 'OperacionController');
Route::get('get-data-operaciones-datatables', ['as'=>'get.operaciones','uses'=>'OperacionController@getData']);
Route::post('operaciones/edit/hbl', 'OperacionController@updateHBL')->name('operaciones/edit/hbl');
/*Agregar detalle de contenedor*/
Route::get('operaciones/dcontainer/{idoperation}/{typeoperation}/{operaciondetail}','OperacionController@createdetails')->name('operaciones.dcontainer');
Route::post('operaciones/addDetails', 'OperacionController@addDetails')->name('operaciones/addDetails');

Route::get('get-data-columns', ['as'=>'get.columns','uses'=>'OperacionController@getColumns']);
Route::post('operaciones-puerto','OperacionController@puertoSearch');
Route::get('autocomplete/fetch', 'OperacionController@puertoSearch')->name('autocomplete.fetch');
Route::get('autocomplete/entidad', 'OperacionController@entidadSearch')->name('autocomplete.entidad');
Route::post('operaciones-files','OperacionController@files');
Route::get('operaciones/view/{file}','OperacionController@viewFile')->name('view.file');
Route::post('operaciones/update/telex', 'OperacionController@telex')->name('operaciones/update/telex');
Route::post('operaciones/restore', 'OperacionController@restorePreOperation')->name('operaciones/restore');


/** operacion detalle contenedor  **/
Route::post('operation/container/store','OperationDetails@store')->name('container.store');
Route::post('operation/container/update','OperationDetails@update')->name('container.update');
Route::post('operation/container/delete','OperationDetails@destroy')->name('container.delete');
Route::get('get-data-container-details', ['as'=>'get.container.details','uses'=>'OperationDetails@getData']);
/** Busqueda por contenedor **/
Route::get('operacion/contenedor/filter','OperationDetails@search')->name('operationdetail.filter');
Route::get('get-containers', ['as'=>'get.containers','uses'=>'OperacionController@getContainer']);
Route::get('get-data-container-filter', ['as'=>'get.container.filter','uses'=>'OperationDetails@getDataDetails']);
/** Retornar vacio contenedor **/
Route::post('operation/container/emptyContainer','OperationDetails@emptyContainer')->name('container.emptyContainer');

Route::post('operation/details/emptyContainer','OperacionDetalleController@emptyContainer')->name('operationdetail.emptyContainer');
Route::get('get-data-operacion-filter', ['as'=>'get.operacion.filter','uses'=>'OperacionDetalleController@getDataDetails']);

/* Demurrage  Reports */

Route::get('report/demurrage', ['as'=>'get.demurrage','uses'=>'ReportDemurrageController@Demurrage']);
Route::post('generate/demurrage', 'ReportDemurrageController@getData')->name('generate/demurrage');
Route::get('demurrage/download/{custom}/{dateStart}/{dateFinish}', 'ReportDemurrageController@generateReportxls')->name('demurrage/download');
/* Demurrage  General */
Route::get('report/general', ['as'=>'get.general','uses'=>'ReportGeneralController@Demurrage']);
Route::post('generate/general', 'ReportGeneralController@getData')->name('generate/general');
Route::get('general/download/{custom}/{dateStart}/{dateFinish}', 'ReportGeneralController@exportGenerate')->name('demurrage/download');


Route::get('report/download', 'ReportDemurrageController@downloadExcel');
/* TTR Report */
Route::get('report/ttr', ['as'=>'get.general','uses'=>'ReportTTRController@Demurrage']);
Route::post('generate/ttr', 'ReportTTRController@getData')->name('generate/general');
Route::get('ttr/download/{custom}/{dateStart}/{dateFinish}', 'ReportTTRController@exportGenerate')->name('demurrage/download');

/* Containers Report */
Route::get('report/containers', ['as'=>'get.containersR','uses'=>'ReportContainersController@index']);


Route::get('containers/download/{custom}/{dateStart}/{dateFinish}', 'ReportContainersController@generateReportxls')->name('demurrage/download');

/*
/* cargos admin */
Route::resource('cargos', 'CargoController');
Route::get('get-data-cargos-datatables', ['as'=>'get.cargos','uses'=>'CargoController@getData']);

Route::get('/users/{user_id}/approve', 'UserController@approve')->name('admin.users.approve');

Route::get('logout', 'Auth\LoginController@logout', function () {
    return abort(404);
});

Route::get('approval', 'HomeController@approval', function () {
    return abort(404);
});

Route::get('mail/operation', 'EmailsController@vista');
//Route::get('mail/send', 'EmailsController@build');
Route::get('mail/send', 'OperacionController@sendMailCreate');
Route::get('excel', 'ReportGeneralController@excel');
Route::get('/export-users', 'ReportGeneralController@importOperation');
Route::get('/export', 'ReportGeneralController@exportUserData');

/* Portal Acceso a Clientes */
Route::resource('customer', 'CustomerController');
Route::get('get-data-customer-datatables', ['as'=>'get.customer','uses'=>'CustomerController@getData']);
Route::post('customer/delete', 'CustomerController@delete')->name('customer/delete');
Route::post('customer/create', 'CustomerController@add')->name('customer/create');

app/Puerto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Puerto extends Model
{
  /**
  * El nombre de la tabla donde se almacena los datos
  * @var String
  * @access protected
  */
  protected $table = 'adm_puertos';

  /**
  * El nombre de la llave primaria
  * @var String
  * @access protected
  */
  protected $primaryKey = 'id';

  /**
   * Los atributos que pueden ingresarlos de forma masiva
   *
   * @var array
   */
  protected $fillable = [
      'puerto',
      'pais',
      'clave_puerto',
      'activo',
  ];

  // establecer un valor predeterminado.
  protected $attributes = array(
    'activo' => 1,
  );

  // tabla relacional
  public function pais()
  {
      return $this->belongsTo('App\Pais','pais');
  }


}

app/Http/Controllers/PuertoController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use App\Puerto;
use App\Pais;
use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use Illuminate\Support\Facades\Auth;
use Session;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Str;

class PuertoController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // Registro de log.
        \Log::info('|::| Puerto Index.', ['Usuario' => Auth::user()]);

         //Get all puertos and pass it to the view
         $puertos = Puerto::count();
         $puertosEnabled = Puerto::where('activo','=',1)->count();
         $puertosDisabled = Puerto::where('activo','=',0)->count();
         return view('puertos.index')->with('puertos', $puertos)->with('puertosEnabled', $puertosEnabled)->with('puertosDisabled', $puertosDisabled);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // Registro de log.
        \Log::info('|::| Muestra el formulario puertos.create para crear un nuevo recurso.', ['Usuario' => Auth::user()]);

        
        $pais = Pais::orderBy('nombre', 'ASC')->get()->pluck('nombre', 'id')->toArray();

        //Get all municipios and show view
        return view('puertos.create', ['pais' => $pais]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Validate fields
        $this->validate($request, [
            'puerto' => 'required|max:50|unique:adm_puertos',
            'pais' => 'required|max:3',
        ],[
            'puerto.required' => 'El campo Nombre de Puerto es requerido!',
            'pais.required' => 'El campo País es requerido!',
            
        ]);

        $puerto = new Puerto();
        $puerto->puerto = Str::upper($request['puerto']);
        $puerto->pais = $request['pais'];
        $puerto->clave_puerto = Str::upper($request['clave_puerto']);
        $puerto->save();

        // Registro en log.
        \Log::info('|::| Recurso Puerto.store recién creado y almacenado.', ['Usuario' => Auth::user(), 'Puerto' => $puerto]);

        // Registro en Bitácora.
        \LogActivity::addToLog('Recurso recién creado: '.$puerto->puerto);

        return redirect()->route('puertos.index')
            ->with('flash_message',
             'Puertos '. $puerto->puerto.' agregada con éxito!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if(!isset($_SERVER['HTTP_REFERER'])){
            Auth::logout();
            return view('errors.forbidden', ['message' => 'No puedes acceder directamente.']);
        }

        // Registro en log.
        \Log::info('|::| Puerto.show - Mostrar el recurso especificado.', ['Usuario' => Auth::user(), 'Id' => decrypt($id)]);
        
        $puerto = Puerto::findOrFail(decrypt($id));
        return view('puertos.show', compact('puerto'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        // Registro en log.
        \Log::info('|::| Puerto.edit - Muestra el formulario para editar el recurso especificado.', ['Usuario' => Auth::user(), 'Id' => decrypt($id)]);

        $puerto = Puerto::findOrFail(decrypt($id));
        $pais = Pais::orderBy('nombre', 'ASC')->get()->pluck('nombre', 'id')->toArray();
        return view('puertos.edit', compact('puerto','pais'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
        //Validate name, email and password fields
        $this->validate($request, [
            'puerto' => 'required|max:50',
            'pais' => 'required|max:3',
        ],[
            'puerto.required' => 'El campo Nombre de Puerto es requerido!',
            'pais.required' => 'El campo País es requerido!',
             
        ]);

        $puerto = Puerto::findOrFail($id);
        $input = array(
            'puerto' => Str::upper($request['puerto']),
            'pais' => $request['pais'],
            'clave_puerto' => Str::upper($request['clave_puerto'])
        );
        
        $request->all();
        $puerto->fill($input)->save();

        // Registro en Bitácora.
        \LogActivity::addToLog('Recurso actualizado: '.$puerto->puerto);
        
        return redirect()->route('puertos.index')
            ->with('flash_message',
             'Puerto '. $puerto->puerto.' actualizada!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        $puerto = Puerto::findOrFail(decrypt($request->idpuerto));
        $puerto->activo = 0;
        $puerto->save();

        // Registro en log.
        \Log::info('|::| Puerto.destroy Elimina el recurso especificado.', ['Usuario' => Auth::user(), 'Contenedor' => $puerto]);

        // Registro en Bitácora.
        \LogActivity::addToLog('Recurso recién eliminado: '.$puerto->puerto);

        return redirect()->route('puertos.index')
            ->with('flash_message',
             'Puerto eliminado con éxito!');
    }

    /**
    * Process ajax request.
    *
    * @return \Illuminate\Http\JsonResponse
    */
    public function getData()
    {
        $showDeleted  = Input::get('showDeleted');

        $puertos = Puerto::where('activo','=',$showDeleted )->get();
        return Datatables::of($puertos)
            ->addColumn('action', function ($puertos) {

                $result = '';

                if ($puertos->activo == 1){

                    if (Auth::user()->hasPermissionTo('Ver'))
                        $result .= " <a href='".route('puertos.show', encrypt($puertos->id))."' class='btn btn-sm btn-warning' data-toggle='tooltip' title='Ver'><i class='fa fa-eye'></i></a> ";

                    if (Auth::user()->hasPermissionTo('Editar'))
                        $result .= " <a href='".route('puertos.edit', encrypt($puertos->id))."' class='btn btn-sm btn-info' data-toggle='tooltip' title='Editar'><i class='fa fa-edit'></i></a>";
    
                    if (Auth::user()->hasPermissionTo('Eliminar'))
                        $result .= " <button type='submit' class='btn btn-sm btn-danger' data-toggle='modal' data-puerto='".encrypt($puertos->id)."' data-title='".$puertos->puerto."' data-target='#confirmDeleteComment'><i class='fa fa-trash-o' aria-hidden='true'></i></button>";
                }

                return $result;
            })
            ->addIndexColumn()
            ->editColumn('puerto', '{{ $puerto }}')
            ->addColumn('paisDesc', function ($query) {
                return $query->Pais['nombre'];
            })
            ->editColumn('id', '{{$id}}')
            ->editColumn('created_at', '{{ Carbon\Carbon::parse($created_at)->format("d-M-y H:i:s") }}')
            ->editColumn('updated_at', '{{ Carbon\Carbon::parse($updated_at)->format("d-M-y H:i:s") }}')
            ->make(true);
    }

    

}

resources/views/puertos/create.blade.php
@extends('adminlte::layouts.app')

@section('main-content')
<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>Puertos<small>Catálogo de Puertos</small></h1>
    <ol class="breadcrumb">
        <li><a href="{{ url('home') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
        <li><a href="{{ url('puertos') }}">Puertos</a></li>
        <li class="active">Agregar</li>
    </ol>
</section>
<!-- /.Content Header (Page header) -->

<!-- Main content -->
<section class="content">

    @if ($errors->any())
    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <h5><i class="icon fa fa-ban"></i> ¡Alerta!</h5>
        <ul>
            @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif

    <div class="row">
        <!-- left column -->
        <div class="col-md-6">
            <!-- general form elements -->
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Nuevo Puerto</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                {{ Form::open(array('url' => 'puertos')) }}
                <div class="box-body">
                        <div class="form-group">
                            {{ Form::label('puerto', 'Nombre de Puerto') }}
                            {!! Form::text('puerto', null, [
                            'class' => 'form-control',
                            'required' => 'required',
                            ]) !!}
                        </div>

                        <div class="form-group">
                                        {{ Form::label('pais', 'País') }}
                                        {{ Form::select('pais',$pais,null,[
                                        'class' => 'form-control','required' => 'required','placeholder' => 'seleccione uno...'],array('name'=>'cargos[]'))}}
                                        
                        </div>   
                        <div class="form-group">
                            {{ Form::label('clave_puerto', 'Clave de Puerto') }}
                            {!! Form::text('clave_puerto', null, [
                            'class' => 'form-control',
                            ]) !!}
                        </div>     

                </div>
                <div class="box-footer">
                    {{ Form::button('<i class="fa fa-save" aria-hidden="true"></i> Guardar', ['class' => 'btn btn-primary', 'type' => 'submit']) }}
                </div>
                {{ Form::close() }}
            </div>
            <!-- /.box -->

        </div>
        <!--/.col (left) -->

    </div>
    <!-- /.row -->
</section>
<!-- /.content -->
@endsection

resources/views/puertos/index.blade.php
@extends('adminlte::layouts.app')

@section('main-content')
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>Puertos<small>Catálogo de Puertos</small></h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('home') }}"><i class="fa fa-dashboard"></i> Inicio</a></li>
    <li class="active">Puertos</li>
  </ol>
</section>
<!-- /.Content Header (Page header) -->

<!-- Main content -->
<section class="content">

  @if(session()->has('flash_message'))
  <div class="alert alert-success alert-dismissible fade in">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <h4><i class="icon fa fa-check"></i> Éxito!</h4>
    {{ session()->get('flash_message') }}
  </div>
  @endif

  <div class="row">
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="info-box">
        <span class="info-box-icon bg-yellow"><i class="fa fa-user"></i></span>
        <div class="info-box-content">
          <span class="info-box-text">Puertos</span>
          <span class="info-box-number">{{ $puertos }}</span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- ./col -->
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="info-box">
        <span class="info-box-icon bg-yellow"><i class="fa fa-fw fa-check"></i></span>
        <div class="info-box-content">
          <span class="info-box-text">Puertos Habilitados</span>
          <span class="info-box-number">{{ $puertosEnabled }}</span>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- ./col -->
    <div class="col-md-3 col-sm-6 col-xs-12">
      <div class="info-box">
        <span class="info-box-icon bg-yellow"><i class="fa fa-fw fa-trash"></i></span>
        <div class="info-box-content">
          <span class="info-box-text">Puertos Eliminados</span>
          <span class="info-box-number">{{ $puertosDisabled }}</span>
          <a href="#" data-filter=".property-sale" class="click"><span>ver Eliminados <i class="fa fa-arrow-circle-right"></i></span></a>
        </div>
        <!-- /.info-box-content -->
      </div>
      <!-- /.info-box -->
    </div>
    <!-- ./col -->
  </div>
  <!-- /.row -->
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-header with-border">
          <h3 class="box-title">Lista de Puertos</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <table id="areas-table" class="table table-striped table-bordered dt-responsive"></table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->

      @can('Crear')
      <a href="{{ URL::to('puertos/create') }}" class="btn btn-success"><i class="fa fa-plus"></i> Agregar Puerto</a>
      @endcan
    </div>
    <!-- /.col -->
  </div>

  <!-- Delete Model -->
  <div id="confirmDeleteComment" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-sm">
      <div class="modal-content">

        <!-- header modal -->
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="mySmallModalLabel">Eliminar Cargo</h4>
        </div>

        <!-- body modal -->
        <div class="modal-body text-center">
          ¿Por favor, confirme que desea eliminar el puerto: <b><span id="fav-title"></span></b>?
          <hr>
          <form action="{{ route('puertos.destroy','1') }}" id="delForm" method="post">
            {{method_field('delete')}} {{csrf_field()}}
            <input name="idpuerto" id="puerto" type="hidden" />
            <input name="_token" type="hidden" value="{{ csrf_token() }}" />
            <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
            <button type="submit" value="delete" class="btn btn-success">Aceptar</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <!-- /.Delete Model -->
</section>

<script>
  $(document).ready(function () {
    // se activa cuando el modal está a punto de ser mostrado.
    $('#confirmDeleteComment').on('show.bs.modal', function (e) {
      var modal = $(this);

      // obtener el atributo idEmpresa del elemento pulsado.
      $("#fav-title").html($(e.relatedTarget).data('title'));
      var idEmpresa = $(e.relatedTarget).data('puerto');
      modal.find('.modal-body #puerto').val(idEmpresa);
    });
  });

  $(function () {
    $('.click').click(function () {
      $("#example").dataTable().fnDestroy();
      loadTable('0'); 
    });
  });
  
  $(function () {
    loadTable('1');
  });

  function loadTable(eliminados) {
    $('#areas-table').DataTable({
      processing: true,
      serverSide: true,
      destroy: true,
      type: 'GET',
      ajax: "{{ route('get.puertos') }}?showDeleted="+eliminados,
      language: {
        "search": "Buscar",
        "lengthMenu": "Mostar _MENU_ registros por página",
        "zeroRecords": "Lo sentimos, no encontramos lo que estas buscando",
        "info": "Mostrando página _PAGE_ de _PAGES_ de _TOTAL_ Registros",
        "infoEmpty": "Registros no encontrados",
        "infoFiltered": "(Filtrado en _MAX_ registros totales)",
        "paginate": {
          "previous": "Anterior",
          "next": "Siguiente",
        },
      },
      columns: [
        {data: 'DT_RowIndex', name: 'DT_RowIndex', title: '#'},
        { data: 'puerto', name: 'puerto', title: 'Puerto' },
        { data: 'paisDesc', name: 'paisDesc', title: 'País' },
        {
          data: 'activo', name: 'activo', title: 'Activo', "render": function (data, type, full, meta) {
            if (data == 1) {
              return '<div class="iradio_flat-green checked" aria-checked="true" aria-disabled="false" style="position: relative;"><input type="radio" name="r3" class="flat-red" checked="" style="position: absolute; opacity: 0;"></div> Habilitada';
            } else {
              return '<div class="iradio_flat-green" aria-checked="false" aria-disabled="false" style="position: relative;"><input type="radio" name="r3" class="flat-red" checked="" style="position: absolute; opacity: 0;"></div> Eliminada';
            }
          }
        },
        { data: 'created_at', name: 'created_at', title: 'Creada' },
        { data: 'updated_at', name: 'updated_at', title: 'Actualizada' },
        { data: 'action', name: 'action', title: 'Acciones', orderable: false, searchable: false }
      ]
    });
  }
</script>
</section>
@endsection

resources/views/puertos/show.blade.php
@extends('adminlte::layouts.app')

@section('main-content')
<!-- Content Header (Page header) -->
<section class="content-header">
  <h1>Puertos<small>Catálogo de Puertos</small></h1>
  <ol class="breadcrumb">
    <li><a href="{{ url('home') }}"><i class="fa fa-ship"></i> Inicio</a></li>
    <li><a href="{{ url('cargos') }}">Puertos</a></li>
    <li class="active">Detalle</li>
  </ol>
</section>
<!-- /.Content Header (Page header) -->
<section class="invoice">
  <!-- title row -->
  <div class="row">
    <div class="col-xs-12">
      <h2 class="page-header">
        <i class="fa fa-ship"></i> {{ $puerto->puerto }}
        <small class="pull-right">Fecha: {{ \Carbon\Carbon::parse($user->from_date)->format('d/m/Y')}}</small>
      </h2>
    </div>
    <!-- /.col -->
  </div>
  <!-- info row -->
  <div class="row invoice-info">
    <div class="col-sm-4 invoice-col">
      Nombre de Puerto:
      <address>
        <strong>{{ $puerto->puerto }}</strong><br>
      </address>
    </div>
    <div class="col-sm-4 invoice-col">
      Pais:
      <address>
        <strong>{{ $puerto->Pais['nombre'] }}</strong><br>
      </address>
    </div>
    <div class="col-sm-4 invoice-col">
      Clave de Puerto:
      <address>
        <strong>{{ $puerto->clave_puerto }}</strong><br>
      </address>
    </div>

    
    <div class="col-sm-4 invoice-col">
      <b>Clave #{{ $puerto->id }}</b><br>
      <br>
      <b>Fecha de Alta:</b> {{ $puerto->created_at }}<br>
      <b>Fecha de Actualización:</b> {{ $puerto->updated_at }}<br>
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
  
  </br>
  <!-- this row will not appear when printing -->
  <div class="row no-print">
    <div class="col-xs-12">
      <a href="#" class="btn btn-info" onClick="window.print()"><i class="fa fa-print"></i> Imprimir</a>
    </div>
  </div>
</section>

<!-- Main content -->
<section class="content">




</section>
@endsection